"""
PDF export functionality for truth cards.

Generates PDF reports from truth cards using WeasyPrint.
"""

from io import BytesIO

from weasyprint import CSS, HTML

from ..models.recon import TruthCard
from ..notify.memo import render_html


def generate_pdf(card: TruthCard) -> bytes:
    """
    Generate a PDF report from a truth card.

    Returns PDF bytes that can be saved to a file or served as download.

    Raises:
        Exception: If PDF generation fails
    """
    try:
        # Render HTML memo
        html_content = render_html(card)

        # Add PDF-specific styling
        pdf_css = CSS(
            string="""
            @page {
                size: letter;
                margin: 1in;
            }
            body {
                font-family: Arial, sans-serif;
                font-size: 12pt;
                line-height: 1.6;
                color: #333;
            }
            h3 {
                color: #0066cc;
                border-bottom: 2px solid #0066cc;
                padding-bottom: 0.5em;
            }
            .discrepancy {
                margin: 1em 0;
                padding: 1em;
                border-left: 4px solid #ccc;
                background-color: #f9f9f9;
                page-break-inside: avoid;
            }
            .severity-high {
                border-left-color: #dc3545;
            }
            .severity-med {
                border-left-color: #ffc107;
            }
            .severity-low {
                border-left-color: #17a2b8;
            }
            ul {
                margin: 0.5em 0;
                padding-left: 2em;
            }
            li {
                margin: 0.25em 0;
            }
            .footer {
                margin-top: 2em;
                padding-top: 1em;
                border-top: 1px solid #ccc;
                font-size: 10pt;
                color: #666;
            }
        """
        )

        # Create full HTML document
        full_html = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Iva Truth Meter - {card.company}</title>
        </head>
        <body>
            {html_content}
            <div class="footer">
                <p>Generated by Iva Reality Layer on {card.generated_at.strftime('%Y-%m-%d %H:%M:%S UTC')}</p>
                <p><small>Advisory only — not legal advice.</small></p>
            </div>
        </body>
        </html>
        """

        # Generate PDF
        pdf_bytes = BytesIO()
        HTML(string=full_html).write_pdf(pdf_bytes, stylesheets=[pdf_css])
        pdf_bytes.seek(0)

        return pdf_bytes.read()
    except Exception as e:
        raise Exception(f"Failed to generate PDF: {str(e)}")


def save_pdf(card: TruthCard, filepath: str) -> None:
    """
    Save a truth card as a PDF file.

    Args:
        card: Truth card to export
        filepath: Path where PDF should be saved
    """
    pdf_bytes = generate_pdf(card)
    with open(filepath, "wb") as f:
        f.write(pdf_bytes)
